/*
 * This source file was generated by the Gradle 'init' task
 */
package dependency.manager;

import java.net.URISyntaxException;
import java.util.Scanner;

import dependency.manager.process.JavaLib;
import dependency.manager.process.NpmLib;
import dependency.manager.process.PythonLib;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws URISyntaxException {
        System.out.println(new App().getGreeting());
        Scanner scanner = new Scanner(System.in);
        System.out.println("실행할 클래스를 선택하세요 (1: JavaLib, 2: NpmLib, 3: PythonLib): ");
        int choice = scanner.nextInt();

        switch (choice) {
            case 1:
                JavaLib.main(args);
                break;
            case 2:
                NpmLib.main(args);
                break;
            case 3:
                PythonLib.main(args);
                break;
            default:
                System.out.println("잘못된 선택입니다.");
        }
    }
}
